---
- hosts: all
  vars:
   devops_password: '$6$0yiefepkUkOhcjgo$oEIS2ltq04.R7ORjR/L8Okt5Hzz6VzzHDwrD.i4RL3rnmVDh.bXR.1yUfeobmrh7Fp4EBmKo2KSeCRTaNfxNA.'
   gather_facts: yes
   remote_user: lorenzo
   become: true

  tasks:
  - name: Add a new user named devops
    user:
      name: devops
      shell: /bin/bash
      password: "{{ devops_password }}"

  - name: Add devops user to the sudoers
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "devops  ALL=(ALL)  NOPASSWD: ALL"

  - name: Deploy SSH Key
    authorized_key: user=devops
                    key="{{ lookup('file', '/home/devops/.ssh/id_rsa.pub') }}"
                    state=present

  - name: Disable Password Authentication
    lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

  - name: Disable Root Login
    lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
    notify:
      - restart ssh

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted

